export const USER_ACTIONS = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  CREATE_PATIENT: "CREATE_PATIENT",
  CREATE_PATIENT_SUCCESS: "CREATE_PATIENT_SUCCESS",
  CREATE_PATIENT_ERROR: "CREATE_PATIENT_ERROR",
};
