export const USER_ACTIONS = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  CREATE_PATIENT: "CREATE_PATIENT",
  CREATE_PATIENT_SUCCESS: "CREATE_PATIENT_SUCCESS",
  CREATE_PATIENT_ERROR: "CREATE_PATIENT_ERROR",
  CREATE_THERAPIST: "CREATE_THERAPIST",
  CREATE_THERAPIST_SUCCESS: "CREATE_THERAPIST_SUCCESS",
  CREATE_THERAPIST_ERROR: "CREATE_THERAPIST_ERROR",
};

export const AVATAR_ACTIONS = {
  CREATE_AVATAR: "CREATE_AVATAR",
  CREATE_AVATAR_SUCCESS: "CREATE_AVATAR_SUCCESS",
  CREATE_AVATAR_ERROR: "CREATE_AVATAR_ERROR",
  GET_AVATAR: "GET_AVATAR",
  GET_AVATAR_SUCCESS: "GET_AVATAR_SUCCESS",
  GET_AVATAR_ERROR: "GET_AVATAR_ERROR",
  CHECK_PIN: "CHECK_PIN",
  CHECK_PIN_SUCCESS: "CHECK_PIN_SUCCESS",
  CHECK_PIN_ERROR: "CHECK_PIN_ERROR",
};

export const MESSAGE_ACTIONS = {
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_ERROR: "SEND_MESSAGE_ERROR",
  GET_MESSAGE: "GET_MESSAGE",
  GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
  GET_MESSAGE_ERROR: "GET_MESSAGE_ERROR",
  VIEW_MESSAGE: "VIEW_MESSAGE",
  VIEW_MESSAGE_SUCCESS: "VIEW_MESSAGE_SUCCESS",
  VIEW_MESSAGE_ERROR: "VIEW_MESSAGE_ERROR",
};
