export const URLS = {
  LOGIN_URL: "/login",
  CREATE_PATIENT_URL: "/savePatient",
  CREATE_AVATAR_URL: "/saveAlter",
  GET_AVATAR_URL: "/getAlters",
  SEND_MESSAGE_URL: "/sendMessage",
  GET_MESSAGE_URL: "/messages",
  VIEW_MESSAGE_URL: "/viewMessage",
  CHECK_PIN_URL: "/validateAlter",
  AVATAR_DETAILS_URL: "/updateAlterDetails",
  CREATE_THERAPIST_URL: "/saveTherapist",
  GET_PATIENTS_URL: "/getPatients",
  COHOST_DETAILS_URL: "/updateAlterAccess",
  COHOST_GETAVATAR_DETAILS: "/getAlterAccessDetails",
  ALTER_PASSWORD_UPDATE_URL: "/updateAlterPassword",
  AVATAR_PROFILE_URL: "/updateAlterProfImg",
  LOGIN_PASSWORD_UPDATE_URL: "/updatePassword",
  GET_ALTER_DETAIL_BYID: "/getAlter",
  SEND_OTP_URL: "/sendOTP",
};
